version: '3.7'

x-common-env: &default-env
  DJANGO_SECRET_KEY: "CHANGEthisIFusingINaPRODUCTIONenvironment"
  HTTPS: 'false'
  DEBUG: 'true'
  SQL_HOST: db
  SQL_PORT: '5432'
  WAIT_FOR_POSTGRES: "true"
  DATABASE_URL: postgres://postgres:postgres@db/postgres
  REDIS_LAYER: "true"
  REDIS_HOST: "redis"
  TRANSFORMERS_CACHE: "/usr/src/transformers/"

services:
  db:
    image: postgres:10.5-alpine
    restart: always
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - ./volumes/redis:/data
    restart: always
  backend:
    image: cf3-ijs-si-backend
    build:
      context: backend/.
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      <<: *default-env
      COLLECTSTATIC: "true"
      MIGRATE: "true"
    ports:
      - 127.0.0.1:8000:8000/tcp
    volumes:
      - ./volumes/files:/usr/src/app/mothra/public/files
      - ./volumes/static:/usr/src/app/mothra/public/static
      - ./volumes/media:/usr/src/app/mothra/public/media
      - ./volumes/transformers:/usr/src/transformers
      - ./volumes/cf_text_embeddings:/root/.cf_text_embeddings
  webapp:
    image: cf3-ijs-si-frontend
    build:
      context: frontend/.
    ports:
      - 127.0.0.1:8080:80/tcp
